name: fedora-sway
description: Lean Fedora Atomic Sway nightly image

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43

modules:
  - type: rpm-ostree
    install:
      - wireguard-tools           # Security VPN
      - fail2ban                  # Security
      - rclone                    # Backup
      - smartmontools
      - iotop
      - gh                        # Github
      - syncthing                 # Synch files
      - zram-generator-defaults
      - rsms-inter-fonts
      - jetbrains-mono-fonts
      - neovim
      - zathura
      - zathura-pdf-mupdf
      - mako                      # Sway native notifications
      - tesseract                 # OCR           
      - tesseract-langpack-eng    # OCR
    remove:
      - firefox
      - firefox-langpacks
      - dunst                     # Non-sway native notifications

  - type: files
    files:
      - source: etc
        destination: /etc/

  - type: default-flatpaks
    configurations:
      - system: true
        notify: true
        install:
          - org.gnome.Loupe                       # Image Viewer
          - org.gnumeric.Gnumeric                 # Spreadsheets
          - de.haeckerfelix.Fragments             # Torrents
          - io.github.celluloid_player.Celluloid  # Video player
          - md.obsidian.Obsidian                  # Wiki .md files
          - com.brave.Browser
          - com.bitwarden.desktop
        remove:
          - org.libreoffice.LibreOffice
          - com.transmissionbt.Transmission
          - org.videolan.VLC

  - type: script
    scripts:
      - setup-keyring
      - cleanup-flatpaks
