name: fedora-sway
description: Lean Fedora Atomic Sway nightly image

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43

modules:
  - type: rpm-ostree
    install:
      - wireguard-tools
      - fail2ban
      - rclone
      - smartmontools
      - iotop
      - gh
      - syncthing
      - zram-generator-defaults
      - rsms-inter-fonts
      - jetbrains-mono-fonts
      - neovim
      - zathura
      - zathura-pdf-mupdf
      - mako
      - tesseract            
      - tesseract-langpack-eng
    remove:
      - firefox
      - firefox-langpacks
      - dunst

  - type: files
    files:
      - source: etc
        destination: /etc/

  - type: default-flatpaks
    configurations:
      - system: true
        notify: true
        install:
          - org.gnome.Loupe
          - org.gnumeric.Gnumeric
          - de.haeckerfelix.Fragments
          - io.github.celluloid_player.Celluloid
          - md.obsidian.Obsidian
          - com.brave.Browser
          - com.bitwarden.desktop
        remove:
          - org.libreoffice.LibreOffice
          - com.transmissionbt.Transmission
          - org.videolan.VLC

  - type: script
    scripts:
      - setup-keyring
      - cleanup-flatpaks
